# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=70, null=True)),
                ('apellido', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('legajo', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('cajones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajon', models.IntegerField()),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Alumno')),
                ('archivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='localizacion',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Lugar'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Lugar'),
        ),
    ]
